c_compiler:
  - vs2015  # [win]
  - gcc  # [linux]
cxx_compiler:
  - vs2015  # [win]
MACOSX_DEPLOYMENT_TARGET:
  - '10.11'  # [osx]
macos_min_version:
  - '10.11'  # [osx]

cudnn:                                    # [linux64]
  - undefined                             # [linux64]
cuda_compiler_version:                    # [linux64]
  - None                                  # [linux64]
docker_image:                             # [linux64]
  - condaforge/linux-anvil-cos7-x86_64    # [linux64]
cdt_name:                                 # [linux64]
  - cos7                                  # [linux64]

pin_run_as_build:
  # libuv is missing run_exports
  libuv:
    max_pin: x.x
    min_pin: x.x.x
